# Set shell to bash for reliable execution
set shell := ["bash", "-uc"]

# Default recipe: show available commands
@default:
    just --list

## ==========================================================
## NixOS Build Management
## ==========================================================

# Rebuild the configuration with build option (default is nixos-rebuild boot)
# Valid 
[group('NixOS')]
rebuild build-option='boot':
    git add -A
    sudo nixos-rebuild {{build-option}} --flake .#

# Rollback to the previous system generation
[group('NixOS')]
rollback:
    sudo nixos-rebuild switch --rollback

# Cleanup and optimize the Nix store
[group('NixOS')]
clean-up:
    sudo nix-collect-garbage
    sudo nix-store --optimise
