# Set shell to bash for reliable execution
set shell := ["bash", "-uc"]

# Default recipe: show available commands
@default:
    just --global-justfile --list

## ==========================================================
## NixOS Build Management
## ==========================================================

# Rebuild NixOS configuration with build option (default is nixos-rebuild switch)
[group('NixOS')]
rebuild build-option='switch':
    git add -A
    sudo nixos-rebuild {{build-option}} --flake .#

# Rollback to the previous system generation
[group('NixOS')]
rollback:
    sudo nixos-rebuild switch --rollback

# Cleanup and optimize the Nix store
[group('NixOS')]
cleanup:
    sudo nix-collect-garbage
    sudo nix-store --optimise
